# Generated by Django 4.2.5 on 2023-10-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, db_column='DATE_TIME', null=True)),
                ('trn_ref', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TRN_REF', max_length=255, null=True)),
                ('batch', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BATCH', max_length=255, null=True)),
                ('txn_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TXN_TYPE', max_length=255, null=True)),
                ('txn_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TXN_ID', max_length=255, null=True)),
                ('issuer', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ISSUER', max_length=255, null=True)),
                ('acquirer', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ACQUIRER', max_length=255, null=True)),
                ('issuer_code', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ISSUER_CODE', max_length=255, null=True)),
                ('acquirer_code', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ACQUIRER_CODE', max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BRANCH_NAME', max_length=255, null=True)),
                ('agentnames', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AGENTNAMES', max_length=255, null=True)),
                ('channel', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CHANNEL', max_length=255, null=True)),
                ('agent_code', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AGENT_CODE', max_length=255, null=True)),
                ('agent_code_alias', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AGENT_CODE_ALIAS', max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, db_column='AMOUNT', decimal_places=2, max_digits=18, null=True)),
                ('acc_no', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ACC_NO', max_length=255, null=True)),
                ('stan', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='STAN', max_length=255, null=True)),
                ('fee', models.DecimalField(blank=True, db_column='FEE', decimal_places=2, max_digits=18, null=True)),
                ('beneficiary_entity', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BENEFICIARY_ENTITY', max_length=255, null=True)),
                ('issuer_commission', models.DecimalField(blank=True, db_column='ISSUER_COMMISSION', decimal_places=2, max_digits=18, null=True)),
                ('acquirer_commission', models.DecimalField(blank=True, db_column='ACQUIRER_COMMISSION', decimal_places=2, max_digits=18, null=True)),
                ('agent_commission', models.DecimalField(blank=True, db_column='AGENT_COMMISSION', decimal_places=2, max_digits=18, null=True)),
                ('response_code', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='RESPONSE_CODE', max_length=255, null=True)),
                ('transaction_status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TRANSACTION_STATUS', max_length=255, null=True)),
                ('acq_flg', models.BooleanField(blank=True, db_column='ACQ_FLG', null=True)),
                ('iss_flg', models.BooleanField(blank=True, db_column='ISS_FLG', null=True)),
                ('acq_flg_date', models.DateTimeField(blank=True, db_column='ACQ_FLG_DATE', null=True)),
                ('iss_flg_date', models.DateTimeField(blank=True, db_column='ISS_FLG_DATE', null=True)),
            ],
            options={
                'db_table': 'Transactions',
                'managed': False,
            },
        ),
        
    ]
