# Generated by Django 4.2.5 on 2023-10-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0002_transactions_alter_reconlog_bank_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconlog',
            name='user_id',
        ),
        
    ]
