# Generated by Django 4.2.5 on 2023-10-11 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recon', '0003_remove_reconlog_user_id_alter_reconlog_bank_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconlog',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        
    ]
